backend:
  name: github
  repo: starknet-io/starknet-website
  branch: dev

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    label_singular: Page
    identifier_field: path
    folder: _data/pages/en
    create: true
    fields:
      - name: path
        label: Path
      - name: title
        label: Title
      - name: body
        label: Body
        widget: markdown
  - name: posts
    label: Posts
    label_singular: Post
    identifier_field: id
    folder: _data/posts/en
    create: true
    fields:
      - name: id
        label: id
      - name: title
        label: Title
      - name: image
        label: Image
        widget: file
      - name: category
        label: Category
        widget: relation
        collection: "categories"
        search_fields: ["name"]
        value_field: "id"
        display_fields: ["name"]
      - name: topic
        label: Topic
        widget: relation
        collection: "topics"
        search_fields: ["name"]
        value_field: "id"
        display_fields: ["name"]
      - name: short_desc
        label: Short Description
        widget: text
      - name: body
        label: Body
        widget: markdown
  - name: topics
    label: Topics
    label_singular: Topic
    identifier_field: id
    folder: _data/topics/en
    create: true
    fields:
      - name: id
        label: id
      - name: name
        label: Name
  - name: categories
    label: Categories
    label_singular: Category
    identifier_field: id
    folder: _data/categories/en
    create: true
    fields:
      - name: id
        label: id
      - name: name
        label: Name
  - name: events
    label: Events
    label_singular: Event
    folder: _data/events/en
    create: true
    fields:
      - name: name
        label: Event Name
      - name: image
        label: Event Image
        widget: file
      - name: start_date
        label: Start Date
        widget: date
      - name: end_date
        label: End Date
        widget: date
      - name: location
        label: Location
        widget: map
      - name: location_name
        label: Location Name
      - name: url
        label: Website URL
  - label: "Settings"
    name: "settings"
    files:
      - label: "Main Menu"
        name: "main-menu"
        file: "_data/settings/en/main-menu.yml"
        fields:
          - label: Pages
            name: pages
            widget: list
            fields:
              - label: Page
                name: page
                widget: relation
                collection: "pages"
                search_fields: ["title"]
                value_field: "path"
                display_fields: ["title"]
              - label: Pages
                name: pages
                widget: list
                fields:
                  - label: Page
                    name: page
                    widget: relation
                    collection: "pages"
                    search_fields: ["title"]
                    value_field: "path"
                    display_fields: ["title"]
                  - label: Pages
                    name: pages
                    widget: list
                    fields:
                      - label: Page
                        name: page
                        widget: relation
                        collection: "pages"
                        search_fields: ["title"]
                        value_field: "path"
                        display_fields: ["title"]
                      - label: Pages
                        name: pages
                        widget: list
                        fields:
                          - label: Page
                            name: page
                            widget: relation
                            collection: "pages"
                            search_fields: ["title"]
                            value_field: "path"
                            display_fields: ["title"]
      - label: "Events Page"
        name: "events-page"
        file: "_data/settings/en/events-page.yml"
        fields:
          - label: Title
            name: title
          - label: Description
            name: description
