name: Build and Deploy Netlify CMS

on:
  push:

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment:
      name: Netlify CMS ${{ github.ref_name }}
      url: https://${{ env.GITHUB_REF_SLUG_URL }}.starknet-netlify-cms.pages.dev
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .eslintcache
            **/tsconfig.tsbuildinfo
            **/.types/**
            **/.types-*/**
          key: build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-cache-

      - name: Install dependencies
        run: yarn

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 28

      - name: Build Netlify CMS
        run: yarn workspace @starknet-io/netlify-cms build
        env:
          VITE_LIVE_PREVIEW_URL: https://${{ env.GITHUB_REF_SLUG_URL }}.starknet-website.pages.dev
          VITE_GIT_BRANCH_NAME: ${{ github.ref_name }}
          VITE_API_BASE_URL: https://${{ env.GITHUB_REF_SLUG_URL }}.starknet-website.pages.dev/api
          VITE_DATA_URL: https://${{ env.GITHUB_REF_SLUG_URL }}.starknet-website.pages.dev/data
          VITE_BACKEND_AUTH_URL: https://auth.clivado.com

      - name: Deploy Netlify CMS
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.NEW_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.NEW_CLOUDFLARE_ACCOUNT_ID }}
          projectName: starknet-netlify-cms
          directory: workspaces/netlify-cms/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
