on:
  push:
    branches:
      - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        pr_title: "Merge dev into production"
        pr_body: |
          ## How to approve and merge this pull request

          As a non-technical team member, follow these steps to review, approve, and merge this pull request:

            - [ ] 1. Review the changes made in this pull request by looking at the "Files changed" tab. Make sure everything looks correct and as expected.
            - [ ] 2. Visit the live preview of the changes at [https://starknet-website-dev.vercel.app/](https://starknet-website-dev.vercel.app/). Ensure the changes are properly implemented and everything is working as expected.
            - [ ] 3. If you are satisfied with the changes, click on the "Review changes" button (usually green) at the top of the pull request page.
            - [ ] 4. In the review summary dialog, select "Approve" and click on "Submit review."

            ðŸ’¡ Remember, you cannot fully approve your own changes. Content reviewers can approve each other's changes, and if only content has changed, a developer is not required to approve. Mention a colleague using their GitHub username (e.g., @username) in the PR comments or directly communicate with them to request their review.

            - [ ] 5. After receiving approval from another team member, click on the "Merge pull request" button.
            - [ ] 6. Optionally, you can add a comment before merging.
            - [ ] 7. Click on "Confirm merge" to finalize the process. The changes will be applied to the production branch, and [starknet.io](http://starknet.io) will be updated within a few minutes.

            If you are unsure about merging something or need any assistance, please ping a developer to double check.

        pr_allow_empty: false
        pr_label: "auto-pr"
        destination_branch: "production"
        github_token: ${{ secrets.GITHUB_TOKEN }}
