name: Build and Deploy Starknet Website

on:
  push:

jobs:
  build:
    name: Build and Deploy
    environment:
      name: Starknet Website ${{ github.ref_name }}
      url: https://${{ env.GITHUB_REF_SLUG_URL }}.starknet-website.pages.dev
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .eslintcache
            **/tsconfig.tsbuildinfo
            **/.types/**
            **/.types-*/**
          key: build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-cache-


      - name: Install dependencies
        run: yarn

      - name: Set date environment variables
        run: |
          echo "YMDHM=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV
          echo "YMDH=$(date +%Y-%m-%d-%H)" >> $GITHUB_ENV
          echo "YMD=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "YM=$(date +%Y-%m)" >> $GITHUB_ENV

      - name: Restore Crowdin Cache
        uses: actions/cache/restore@v3
        with:
          path: _crowdin
          key: crowdin-cache-dev

      - name: Restore social media data
        uses: actions/cache/restore@v3
        with:
          path: _social-media
          key: sm-cache-${{ github.ref_name }}-${{ env.YMDHM }}
          restore-keys: |
            sm-cache-${{ github.ref_name }}-${{ env.YMDH }}
            sm-cache-${{ github.ref_name }}-${{ env.YMD }}
            sm-cache-${{ github.ref_name }}-${{ env.YM }}
            sm-cache-${{ github.ref_name }}
            sm-cache-

      - name: Update dynamic data
        run: yarn workspace @starknet-io/cms-scripts update-dynamic-data

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 28

      - name: Build project
        run: yarn workspace @starknet-io/website build
        env:
          VITE_SITE_URL: https://${{ env.GITHUB_REF_SLUG_URL }}.starknet-website.pages.dev
          VITE_ALGOLIA_INDEX: ${{ github.ref_name == 'production' && 'production' || 'dev' }}
          VITE_ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          VITE_ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          VITE_CF_STREAM_URL: ${{ secrets.CF_STREAM_URL }}

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: starknet-website
          directory: dist/client
          workingDirectory: workspaces/website
          wranglerVersion: '3'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name == 'production' && 'main' || github.ref_name }}

